apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/ks.yaml
  - cloudflared/ks.yaml
  - keda/ks.yaml
  - longhorn/ks.yaml
  - external-secrets/ks.yaml
  - cluster-secret-store/ks.yaml
